src/Entity/Facturer.php
<?php

namespace App\Entity;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\FacturerRepository;
use DateTime;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Validator\Constraints\length;
use Symfony\Component\Serializer\Annotation\Groups ;

#[ORM\Entity(repositoryClass: FacturerRepository::class)]
class Facturer
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name: "id_facture")]
    #[Groups(['posts:read'])]
        private ?int $id_facture;

    #[ORM\Column]
    #[Groups(['posts:read'])]
    private ?DateTime $dateFacture;

    #[ORM\Column(length : 255)]
    #[Groups(['posts:read'])]
    private ?string $statut;

    #[ORM\Column(length : 255)]
    #[Groups(['posts:read'])]
    private ?string $notes;

    

    public function getId_Facture(): ?int
    {
        return $this->id_facture;
    }

    public function getDateFacture(): ?DateTime
    {
        return $this->dateFacture;
    }

    public function setDateFacture(DateTime $dateFacture): self
    {
        $this->dateFacture = $dateFacture;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(string $notes): self
    {
        $this->notes = $notes;

        return $this;
    }

    public function getIdFacture(): ?int
    {
        return $this->id_facture;
    }


 


}

src/Form/FacturerType.php
<?php

namespace App\Form;

use App\Entity\Facturer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FacturerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('dateFacture')
            ->add('statut')
            ->add('notes')
            ->add('ajouter',SubmitType::class)
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Facturer::class,
        ]);
    }
}

src/Controller/FacturerController.php
<?php

namespace App\Controller;

use App\Entity\Facturer;
use App\Form\FacturerType;
use App\Repository\FacturerRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use MercurySeries\FlashyBundle\FlashyNotifier;

#[Route('/facturer')]
class FacturerController extends AbstractController
{
    #[Route('/', name: 'app_facturer_index', methods: ['GET'])]
    public function index(FacturerRepository $facturerRepository,FlashyNotifier $flashy): Response
    {
        $flashy->success('Liste des factures!', 'http://your-awesome-link.com');

        return $this->render('facturer/index.html.twig', [
            'facturers' => $facturerRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_facturer_new', methods: ['GET', 'POST'])]
    public function new(Request $request, FacturerRepository $facturerRepository): Response
    {
        $facturer = new Facturer();
        $form = $this->createForm(FacturerType::class, $facturer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $facturerRepository->save($facturer, true);

            return $this->redirectToRoute('app_facturer_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('facturer/new.html.twig', [
            'facturer' => $facturer,
            'form' => $form,
        ]);
    }

    #[Route('/{id_facture}', name: 'app_facturer_show', methods: ['GET'])]
    public function show(Facturer $facturer): Response
    {
        return $this->render('facturer/show.html.twig', [
            'facturer' => $facturer,
        ]);
    }

    #[Route('/{id_facture}/edit', name: 'app_facturer_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Facturer $facturer, FacturerRepository $facturerRepository): Response
    {
        $form = $this->createForm(FacturerType::class, $facturer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $facturerRepository->save($facturer, true);

            return $this->redirectToRoute('app_facturer_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('facturer/edit.html.twig', [
            'facturer' => $facturer,
            'form' => $form,
        ]);
    }

    #[Route('/{id_facture}', name: 'app_facturer_delete', methods: ['POST'])]
    public function delete(Request $request, Facturer $facturer, FacturerRepository $facturerRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$facturer->getId_Facture(), $request->request->get('_token'))) {
            $facturerRepository->remove($facturer, true);
        }

        return $this->redirectToRoute('app_facturer_index', [], Response::HTTP_SEE_OTHER);
    }














    /**
     * @Route("/r/search_user", name="app_facturer_search_user", methods={"GET"})
     */

     public function search_usere(Request $request,NormalizerInterface $Normalizer,FacturerRepository $hrp ): Response
     {
 
         $requestString=$request->get('searchValue');
         $requestString3=$request->get('orderid');
         $user = $hrp->findUser($requestString,$requestString3);
         $jsoncontentc =$Normalizer->normalize($user,'json',['groups'=>'posts:read']); 
         $jsonc=json_encode($jsoncontentc);
         if(  $jsonc == "[]" ) { return new Response(null); }
         else{ return new Response($jsonc); }
 
     }












}

templates/facturer/_delete_form.html.twig
<form method="post" action="{{ path('app_facturer_delete', {'id_facture': facturer.id_facture}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ facturer.id_facture) }}">
    <button class="btn">Delete</button>
</form>

templates/facturer/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/facturer/edit.html.twig
{% extends 'pricing.html.twig' %}

{% block title %}Edit Facturer{% endblock %}

{% block body %}
    <h1>Edit Facturer</h1>

    {{ include('facturer/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_facturer_index') }}">back to list</a>

    {{ include('facturer/_delete_form.html.twig') }}
{% endblock %}

templates/facturer/index.html.twig
{% extends 'pricing.html.twig' %}

{% block title %}Facturer index{% endblock %}

{% block body %}




<link rel="stylesheet" href="{{ asset('bundles/mercuryseriesflashy/css/flashy.css') }}">




<div id="divs" class="app-search">
    <div class="row">
    <input style="padding-right: 20px" class="form-control" type="text" id="search" placeholder="Rechercher par Stauts...🔎">

    </div>
</div>













    <h1>Facturer index</h1>

    <table  id="t" class="table">
        <thead>
            <tr>
                <th>Id_facture</th>
                <th>DateFacture</th>
                <th>Statut</th>
                <th>Notes</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody id="all">
            {% for facturer in facturers %}
            <tr>
                <td>{{ facturer.idFacture }}</td>
                <td>{{ facturer.dateFacture ? facturer.dateFacture|date('Y-m-d') : '' }}</td>
                <td>{{ facturer.statut }}</td>
                <td>{{ facturer.notes }}</td>
                <td>
                    <a href="{{ path('app_facturer_show', {'id_facture': facturer.id_facture}) }}">show</a>
                    <a href="{{ path('app_facturer_edit', {'id_facture': facturer.id_facture}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>

        <tbody id="search">

        </tbody>
    </table>

    <a href="{{ path('app_facturer_new') }}">Create new</a>








































    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $( document ).ready(function() {
    
            
            $("#divs").keyup(function(e){
                var value = $("#search").val();
                if(value.length >= 1 || value.length == 0  )
                {
    
                    //    alert(value);
                    
                    $.ajax({
                        url : "{{ path('app_facturer_search_user') }}",
                       
                        type : 'GET',
                        data: {
                            'searchValue' : value
                        },
                        /*Cette fonction permet de vider le contenu du tableau pour recevoir le nouveau contenu*/
                        success : function(retour){
                            if(retour){
                                $('#t tbody#search').empty();
                                $.each(JSON.parse(retour), function(i, obj) {
                                    $('#t tbody#all').hide();
                                    $('#t tbody#search').append('<tr><td>    '+obj.id_facture+'  </td> <td>'+obj.dateFacture.substring(0,10)+' </td>      <td>'+obj.statut+' </td>              <td>'+obj.notes+' </td>         <td> <a href="/modifier_hotel/'+obj.id+'"><i class="fa fa-pencil" style="color:#ff5b5b;font-size:20px"></i> </a> </td> <td> <a href="/supprimer_hotel/'+obj.id+'"><i class="fa fa-trash" style="color:#00aff0;font-size:20px"></i></a> </td> <td> <a href="/detail_hotel/'+obj.id+'"><i class="fa fa-list" style="color:#00aff0;font-size:20px"></i></a> </td>  </tr>');
                                });
                            }
                            else
                            {
    
                                $('#t tbody#all').show();
                                $('#t tbody#search').empty();
                                $('#t tbody#search').fadeIn('fast');
    
                            }
                        },
                    });
                    return false;
                }
            });
           
    
    
          
            $("#idup").click(function(e){
                var value = $("#search").val();
                var value3 ="ASC";
    
                //    alert(value);
                $.ajax({
                    url : "{{ path('app_facturer_search_user') }}",
                    type : 'GET',
                    data: {
                        'searchValue' : value,
                        'orderid': value3
                    },
                    success : function(retour){
                        if(retour){
                            $('#t tbody#search').empty();
                            $.each(JSON.parse(retour), function(i, obj) {
                                $('#t tbody#all').hide();
                                $('#t tbody#search').append('<tr><td>    '+obj.id_facture+'  </td> <td>'+obj.dateFacture.substring(0,10)+' </td>      <td>'+obj.statut+' </td>              <td>'+obj.notes+' </td>         <td> <a href="/modifier_hotel/'+obj.id+'"><i class="fa fa-pencil" style="color:#ff5b5b;font-size:20px"></i> </a> </td> <td> <a href="/supprimer_hotel/'+obj.id+'"><i class="fa fa-trash" style="color:#00aff0;font-size:20px"></i></a> </td> <td> <a href="/detail_hotel/'+obj.id+'"><i class="fa fa-list" style="color:#00aff0;font-size:20px"></i></a> </td>  </tr>');
                            });
                        }
                        else
                        {
                            $('#t tbody#all').show();
                            $('#t tbody#search').empty();
                            $('#t tbody#search').fadeIn('fast');
                        }
                    },
                });
                return false;
    
            });
          
    
      
            $("#iddown").click(function(e){
                /* La variable value va prendre la valeur insérer dans le champ de texte afin d’effectuer la recherche */
                var value = $("#search").val();
                var value3 ="DESC";
    
                //    alert(value);
                /* Ajax est lancé lors du remplissage du champ texte dont l’id est « search » pour faire la recherche */
                $.ajax({
                    /* l’url est une chaine de caractères contenant l’adresse où la requête est envoyée */
                    url : "{{ path('app_facturer_search_user') }}",
                    /* La méthode utilisée pour transférer les données est GET */
                    type : 'GET',
                    /*Ici search value va prendre la chaine entrée par un utilisateur dans la zone de recherche et sera placée après l’url */
                    data: {
                        'searchValue' : value,
                        'orderid': value3
                    },
                    /*Cette fonction permet de vider le contenu du tableau pour recevoir le nouveau contenu*/
                    success : function(retour){
                        if(retour){
                            $('#t tbody#search').empty();
                            $.each(JSON.parse(retour), function(i, obj) {
                                $('#t tbody#all').hide();
                                $('#t tbody#search').append('<tr><td>    '+obj.id_facture+'  </td> <td>'+obj.dateFacture.substring(0,10)+' </td>      <td>'+obj.statut+' </td>              <td>'+obj.notes+' </td>         <td> <a href="/modifier_hotel/'+obj.id+'"><i class="fa fa-pencil" style="color:#ff5b5b;font-size:20px"></i> </a> </td> <td> <a href="/supprimer_hotel/'+obj.id+'"><i class="fa fa-trash" style="color:#00aff0;font-size:20px"></i></a> </td> <td> <a href="/detail_hotel/'+obj.id+'"><i class="fa fa-list" style="color:#00aff0;font-size:20px"></i></a> </td>  </tr>');
                            });
                        }
                        else
                        {
                            $('#t tbody#all').show();
                            $('#t tbody#search').empty();
                            $('#t tbody#search').fadeIn('fast');
                        }
                    },
                });
                return false;
    
            });
        
        });
    </script>
    
    






    <!-- Flashy depends on jQuery -->
    <script src="//code.jquery.com/jquery.js"></script>
    <!-- Load Flashy default JavaScript -->
    <script src="{{ asset('bundles/mercuryseriesflashy/js/flashy.js') }}"></script>
    <!-- Include Flashy default partial -->
    {{ include('@MercurySeriesFlashy/flashy.html.twig') }}







{% endblock %}

templates/facturer/new.html.twig
{% extends 'pricing.html.twig' %}

{% block title %}New Facturer{% endblock %}

{% block body %}
    <h1>Create new Facturer</h1>

    {{ include('facturer/_form.html.twig') }}

    <a href="{{ path('app_facturer_index') }}">back to list</a>

  




{% endblock %}

templates/facturer/show.html.twig
{% extends 'pricing.html.twig' %}

{% block title %}Facturer{% endblock %}

{% block body %}
    <h1>Facturer</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id_facture</th>
                <td>{{ facturer.idFacture }}</td>
            </tr>
            <tr>
                <th>DateFacture</th>
                <td>{{ facturer.dateFacture ? facturer.dateFacture|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Statut</th>
                <td>{{ facturer.statut }}</td>
            </tr>
            <tr>
                <th>Notes</th>
                <td>{{ facturer.notes }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_facturer_index') }}">back to list</a>

    <a href="{{ path('app_facturer_edit', {'id_facture': facturer.id_facture}) }}">edit</a>

    {{ include('facturer/_delete_form.html.twig') }}
{% endblock %}