src/Entity/Promotion.php
<?php

namespace App\Entity;

use App\Repository\PromotionRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PromotionRepository::class)]
class Promotion
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Il faut Ajouter un nom")]
    private ?string $nomP = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"Il faut Ajouter un duree")]
    private ?int $DureeP = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"Il faut Ajouter un prix avant")]
    private ?int $PrixAvant = null;

    #[ORM\Column]
    #[Assert\NotBlank(message:"Il faut Ajouter un prix apres")]
    private ?int $PrixApres = null;

    #[ORM\Column]
    private ?int $Pourcentage = null;

    #[ORM\ManyToOne(targetEntity: Offre::class, inversedBy: 'products')]
    private $offre;

    public function getOffre(): ?Offre
    {
        return $this->offre;
    }

    public function setOffre(?Offre $offre): self
    {
        $this->offre = $offre;

        return $this;
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomP(): ?string
    {
        return $this->nomP;
    }

    public function setNomP(string $nomP): self
    {
        $this->nomP = $nomP;

        return $this;
    }

    public function getDureeP(): ?int
    {
        return $this->DureeP;
    }

    public function setDureeP(int $DureeP): self
    {
        $this->DureeP = $DureeP;

        return $this;
    }

    public function getPrixAvant(): ?int
    {
        return $this->PrixAvant;
    }

    public function setPrixAvant(int $PrixAvant): self
    {
        $this->PrixAvant = $PrixAvant;

        return $this;
    }

    public function getPrixApres(): ?int
    {
        return $this->PrixApres;
    }

    public function setPrixApres(int $PrixApres): self
    {
        $this->PrixApres = $PrixApres;

        return $this;
    }

    public function getPourcentage(): ?int
    {
        return $this->Pourcentage;
    }

    public function setPourcentage(int $Pourcentage): self
    {
        $this->Pourcentage = $Pourcentage;

        return $this;
    }
}

src/Form/PromotionType.php
<?php

namespace App\Form;

use App\Entity\Promotion;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PromotionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nomP')
            ->add('DureeP')
            ->add('PrixAvant')
            ->add('PrixApres')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Promotion::class,
        ]);
    }
}

src/Controller/PromotionController.php
<?php

namespace App\Controller;

use App\Entity\Promotion;
use App\Form\PromotionType;
use App\Repository\PromotionRepository;
use App\Repository\OffreRepository;
use CMEN\GoogleChartsBundle\GoogleCharts\Charts\PieChart;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/promotion')]
class PromotionController extends AbstractController
{

    #[Route('/chart', name: 'my_chart')]
    public function myChart(PromotionRepository $promotionRepository): Response
    {


        $entityManager = $this->getDoctrine()->getManager();

// Create a new QueryBuilder instance for the Promotion entity
        $queryBuilder = $entityManager->createQueryBuilder();
        $queryBuilder->select('AVG(p.Pourcentage) as avg_discount, COUNT(p.id) as total_promotions, SUM(p.PrixAvant - p.PrixApres) as total_discounts')
            ->from('App\Entity\Promotion', 'p')
            ->where('p.DureeP >= :today')
            ->setParameter('today', new \DateTime());

// Execute the query and fetch the results
        $results = $queryBuilder->getQuery()->getResult();

// Get the average discount percentage, total number of promotions, and total discount amount from the results
        $avgDiscount = $results[0]['avg_discount'];
        $totalPromotions = $results[0]['total_promotions'];
        $totalDiscounts = $results[0]['total_discounts'];

// Render the statistics as a Google Chart
        $chartData = [
            ['Stat', 'Value'],
            ['Average Discount Percentage', $avgDiscount],
            ['Total Promotions', $totalPromotions],
            ['Total Discounts', $totalDiscounts],
        ];
        //$chartData->setElementID('my');

        // dd($pieChart);
        return $this->render('promotion/chart.html.twig', [
            'piechart' => $chartData,

            'promotions' => $promotionRepository->findAll(),
        ]);
    }
    #[Route('/', name: 'app_promotion_index', methods: ['GET'])]
    public function index(PromotionRepository $promotionRepository): Response
    {
        return $this->render('promotion/index.html.twig', [
            'promotions' => $promotionRepository->findAll(),
        ]);
    }

    #[Route('/front', name: 'app_promotion_front', methods: ['GET'])]
    public function indexfront(PromotionRepository $promotionRepository): Response
    {
        return $this->render('promotion/front.html.twig', [
            'promotions' => $promotionRepository->findAll(),
        ]);
    }

// notification
    #[Route('/new/{id}', name: 'app_promotion_new', methods: ['GET', 'POST'])]
    public function new(Request $request,OffreRepository $offreRepository, PromotionRepository $promotionRepository,$id): Response
    {
        $promotion = new Promotion();
        $promotion->setOffre($offreRepository->find($id));
        $form = $this->createForm(PromotionType::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $promotion->setPourcentage(($promotion->getPrixApres()/$promotion->getPrixAvant())*100);
            $promotionRepository->save($promotion, true);

            return $this->redirectToRoute('app_promotion_index', [], Response::HTTP_SEE_OTHER);
        }
      //  $flashy->success('Ajouter Avec Succes');

        return $this->renderForm('promotion/new.html.twig', [
            'promotion' => $promotion,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_promotion_show', methods: ['GET'])]
    public function show(Promotion $promotion): Response
    {
        return $this->render('promotion/show.html.twig', [
            'promotion' => $promotion,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_promotion_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Promotion $promotion, PromotionRepository $promotionRepository): Response
    {
        $form = $this->createForm(PromotionType::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $promotionRepository->save($promotion, true);

            return $this->redirectToRoute('app_promotion_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('promotion/edit.html.twig', [
            'promotion' => $promotion,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_promotion_delete', methods: ['POST'])]
    public function delete(Request $request, Promotion $promotion, PromotionRepository $promotionRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$promotion->getId(), $request->request->get('_token'))) {
            $promotionRepository->remove($promotion, true);
        }

        return $this->redirectToRoute('app_promotion_index', [], Response::HTTP_SEE_OTHER);
    }







}

templates/promotion/_delete_form.html.twig
<form method="post" action="{{ path('app_promotion_delete', {'id': promotion.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ promotion.id) }}">
    <button class="btn">Delete</button>
</form>

templates/promotion/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/promotion/chart.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div id="chart_div"></div>

    {% block javascripts %}
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
        <script type="text/javascript">
            google.charts.load('current', {'packages':['corechart']});
            google.charts.setOnLoadCallback(drawChart);

            function drawChart() {
                var data = google.visualization.arrayToDataTable([
                    ['Promotion', 'Pourcentage'],
                    {% for promotion in promotions %}
                    ['{{ promotion.nomP }}', {{ promotion.pourcentage }}],
                    {% endfor %}
                ]);

                var options = {
                    title: 'Promotions',
                };

                var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
                chart.draw(data, options);
            }
        </script>
    {% endblock %}
{% endblock %}

templates/promotion/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Promotion{% endblock %}

{% block body %}
    <div class="container-fluid pt-4 px-4">
        <div class="bg-secondary rounded-top p-4">
            <div class="row">
                <h6 class="mb-4">Modifier une Nouvelle Promotion</h6>
                {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
                <div class="mb-3">
                    Nom:
                    {{ form_widget(form.nomP, {'attr': {'class': 'form-control'}}) }}
                    {{ form_errors(form.nomP) }}
                </div>
                <div class="mb-3">
                    Duree:
                    {{ form_widget(form.DureeP, {'attr': {'class': 'form-control'}}) }}
                    {{ form_errors(form.DureeP) }}
                </div>
                <div class="mb-3">
                    Prix Avant :
                    {{ form_widget(form.PrixAvant, {'attr': {'class': 'form-control'}}) }}
                    {{ form_errors(form.PrixAvant) }}
                </div>

                <div class="mb-3">
                    Prix Aprés :
                    {{ form_widget(form.PrixApres, {'attr': {'class': 'form-control'}}) }}
                    {{ form_errors(form.PrixApres) }}
                </div>

                <button type="submit" class="btn btn-outline-primary w-100 m-2" formnovalidate>Créer</button>
                {{ form_end(form) }}
            </div>
        </div>
    </div>

{% endblock %}

templates/promotion/front.html.twig
{% extends 'front2.html.twig' %}

{% block title %}Nos Promtions {% endblock %}
{% block body %}

    {% for promotion in promotions %}
    <div class="item">
        <div class="car-wrap rounded ftco-animate">
            <div class="img rounded d-flex align-items-end" style="background-image: url({{ asset('front/images/car-1.jpg') }});">
            </div>
            <div class="text">
                <h2 class="mb-0"><a href="#"></a></h2>
                <div class="d-flex mb-3">
                    <span >{{ promotion.nomP }}</span>
                    <p class="price ml-auto">{{ promotion.DureeP }} <span>day</span></p>
                </div>
            </div>
             <a href="{{ path('app_offre_front', {'id': promotion.offre.id}) }}"class="btn btn-primary"style="background-color: #19B151;border-color: #19B151;">Consulter Offre</a>

        </div>
    </div>
{% endfor %}


{% endblock %}

templates/promotion/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Promotion {% endblock %}

{% block body %}

    <script src="//code.jquery.com/jquery.js"></script>
    <!-- Load Flashy default JavaScript -->
    <script src="{{ asset('bundles/mercuryseriesflashy/js/flashy.js') }}"></script>
    <!-- Include Flashy default partial -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function(){
            $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#rech tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
    <link rel="stylesheet" href="{{ asset('bundles/mercuryseriesflashy/css/flashy.css') }}">

<div style="display: flex; justify-content: space-between;">
    <h1>Promotion</h1><br><br>



</div>
    <input class="form-control" id="myInput" type="text" id="navbar-search-input" placeholder="Search now" aria-label="search" aria-describedby="search">

    <table class="table">
        <thead>
            <tr>
                <th>NomP</th>
                <th>DureeP</th>
                <th>PrixAvant</th>
                <th>PrixApres</th>
                <th>Pourcentage</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody id="rech">

       {% for promotion in promotions %}
            <tr>
                <td>{{ promotion.nomP }}</td>
                <td>{{ promotion.DureeP }}</td>
                <td>{{ promotion.PrixAvant }}</td>
                <td>{{ promotion.PrixApres }}</td>
                <td>{{ promotion.Pourcentage }}</td>
                <td>
                    <a href="{{ path('app_promotion_show', {'id': promotion.id}) }}" class="btn btn-primary"style="background-color: #3330FF;border-color: #3330FF;"><i class="far fa-eye"></i></a>
                    <a href="{{ path('app_promotion_edit', {'id': promotion.id}) }}"class="btn btn-primary"style="background-color: #19B151;border-color: #19B151;"><i class="fas fa-pencil-alt"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div style="position: fixed; bottom: 10px; width: 100%; !important;">
    {# {% set flashyOptions = { 'position': 'bottom', 'important': true } %}
    {{ include('@MercurySeriesFlashy/flashy.html.twig', flashyOptions) }} #}
    </div>
{% endblock %}

templates/promotion/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Promotion{% endblock %}

{% block body %}
    <div class="container-fluid pt-4 px-4">
        <div class="bg-secondary rounded-top p-4">
            <div class="row">
                <h6 class="mb-4">Ajouter une Nouvelle Promotion</h6>
                {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
                <div class="mb-3">
                    Nom:
                    {{ form_widget(form.nomP, {'attr': {'class': 'form-control'}}) }}
                    {{ form_errors(form.nomP) }}
                </div>
                <div class="mb-3">
                    Duree:
                    {{ form_widget(form.DureeP, {'attr': {'class': 'form-control'}}) }}
                    {{ form_errors(form.DureeP) }}
                </div>
                <div class="mb-3">
                    Prix Avant :
                    {{ form_widget(form.PrixAvant, {'attr': {'class': 'form-control'}}) }}
                    {{ form_errors(form.PrixAvant) }}
                </div>

                <div class="mb-3">
                    Prix Aprés :
                    {{ form_widget(form.PrixApres, {'attr': {'class': 'form-control'}}) }}
                    {{ form_errors(form.PrixApres) }}
                </div>

                <button type="submit" class="btn btn-outline-primary w-100 m-2" formnovalidate>Créer</button>
                {{ form_end(form) }}
            </div>
        </div>
    </div>

{% endblock %}

templates/promotion/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Promotion{% endblock %}

{% block body %}
    <h1>Promotion</h1>

    <table class="table">
        <tbody>

            <tr>
                <th>NomP</th>
                <td>{{ promotion.nomP }}</td>
            </tr>
            <tr>
                <th>DureeP</th>
                <td>{{ promotion.DureeP }}</td>
            </tr>
            <tr>
                <th>PrixAvant</th>
                <td>{{ promotion.PrixAvant }}</td>
            </tr>
            <tr>
                <th>PrixApres</th>
                <td>{{ promotion.PrixApres }}</td>
            </tr>
            <tr>
                <th>Pourcentage</th>
                <td>{{ promotion.Pourcentage }}</td>
            </tr>
           <tr>
                <th>Offre Description</th>
                <td>{{ promotion.offre.description }}</td>
            </tr>
            <tr>
                <th>Offre Duree</th>
                <td>{{ promotion.offre.dureeO }}</td>
            </tr>

        </tbody>
    </table>

   <a href="{{ path('app_promotion_index') }}" class="btn btn-primary float-right">
    <i class="fas fa-arrow-left
    "></i> Back to list
</a>

    <a href="{{ path('app_promotion_edit', {'id': promotion.id}) }}">edit</a>

    {{ include('promotion/_delete_form.html.twig') }}
{% endblock %}